import { afterEach, describe, expect, it } from 'vitest';
import { canonicalJson } from '@agent-integrity/core';
import { rename, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { loadTrustedVerificationContext, parseVerificationInput } from '../src/trusted-context.js';
import { cleanupTask7Fixtures, fixture, verificationLimits } from './support/task7-fixture.js';
afterEach(cleanupTask7Fixtures);
describe('snapshot-only trusted context', () => {
 it('loads independent trusted policy and deeply freezes context', async () => { const f=await fixture(); const c=await loadTrustedVerificationContext(parseVerificationInput(f.input)); expect(c.projectRoot).toBe(f.snapshot.projectRoot); expect(Object.isFrozen(c)).toBe(true); expect(Object.isFrozen(c.trustedPolicy.rules.requireEvidenceFor)).toBe(true); });
 it.each([{projectRoot:'project'},{maxSourceBytes:undefined},{maxSourceBytes:0},{maxSourceBytes:'1024'},{maxSourceBytes:1048577},{maxTotalSourceBytes:4194305},{allowedRoots:['../outside']},{allowedRoots:['docs','docs']},{allowedRoots:['other']},{decisionRegistryPath:'../outside.yaml'},{decisionRegistryPath:'integrity/other.yaml'}])('rejects unsafe or unbound config %o',async change=>{const f=await fixture('pass',change);await expect(loadTrustedVerificationContext(parseVerificationInput(f.input))).rejects.toThrow();});
 it.each(['digest','size','unlisted','decision'])('rejects current envelope %s binding drift',async kind=>{const f=await fixture();if(kind==='digest')f.envelope.sources[0].sha256='0'.repeat(64);if(kind==='size')f.envelope.sources[0].size++;if(kind==='unlisted')f.envelope.sources[0].path='docs/unlisted.md';if(kind==='decision')f.envelope.decisionRegistryDigest='0'.repeat(64);await expect(loadTrustedVerificationContext(parseVerificationInput({...f.input,canonicalEnvelope:canonicalJson(f.envelope)}))).rejects.toThrow();});
 it.each(['policy','config','source'])('rejects %s byte ceilings',async kind=>{const f=await fixture();const limits={...verificationLimits,...(kind==='policy'?{maxPolicyBytes:1}:kind==='config'?{maxConfigBytes:1}:{maxSourceBytes:1})};await expect(loadTrustedVerificationContext(parseVerificationInput({...f.input,limits}))).rejects.toThrow();});
 it('cannot redirect policy outside snapshot using symlink',async()=>{const f=await fixture();await rename(f.snapshot.policyFile,f.snapshot.policyFile+'.old');await symlink(f.snapshot.policyFile+'.old',f.snapshot.policyFile);await expect(loadTrustedVerificationContext(parseVerificationInput(f.input))).rejects.toThrow();});
 it('rejects changed private bytes and ignores incoming policy changes',async()=>{const f=await fixture();await writeFile(join(f.root,'incoming','bundle','project','integrity','policy.yaml'),'invalid');await expect(loadTrustedVerificationContext(parseVerificationInput(f.input))).resolves.toBeDefined();await writeFile(f.snapshot.policyFile,'invalid');await expect(loadTrustedVerificationContext(parseVerificationInput(f.input))).rejects.toThrow();});
 it('rejects policy mismatch',async()=>{const f=await fixture('pass',{},p=>p.rules.contradictions='block');await expect(loadTrustedVerificationContext(parseVerificationInput(f.input))).rejects.toThrow();});
 it('rejects capabilities, accessors and noncanonical envelope',async()=>{const f=await fixture();expect(()=>parseVerificationInput({...f.input,receiptStore:{}})).toThrow();let called=false;const hostile={...f.input};Object.defineProperty(hostile,'snapshotRoot',{enumerable:true,get(){called=true;return '/';}});expect(()=>parseVerificationInput(hostile)).toThrow();expect(called).toBe(false);expect(()=>parseVerificationInput({...f.input,canonicalEnvelope:JSON.stringify(f.envelope)})).toThrow();});
 it('enforces host item and input-byte bounds',async()=>{const f=await fixture();expect(()=>parseVerificationInput({...f.input,limits:{...verificationLimits,maxInputBytes:1}})).toThrow();expect(()=>parseVerificationInput({...f.input,limits:{...verificationLimits,maxItems:1},canonicalEnvelope:f.input.canonicalEnvelope.replace('"decisionIds":[]','"decisionIds":["one","two"]')})).toThrow();});
});
